name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for file in build/libs/*
          do gh release upload ${{ github.ref_name }} $file
          done
      - name: Upload to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth