name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth
      - name: Upload to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for file in build/libs/*
          do gh release upload ${{ github.ref_name }} $file
          done